// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gwdat_terrain
#ifndef GRPC_gwdat_5fterrain__INCLUDED
#define GRPC_gwdat_5fterrain__INCLUDED

#include "gwdat_terrain_generated.h"
#include "flatbuffers/grpc.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace GWDat {

class TerrainService final {
 public:
  static constexpr char const* service_full_name() {
    return "GWDat.TerrainService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetTerrain(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, flatbuffers::grpc::Message<TerrainReply>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<TerrainReply>>> AsyncGetTerrain(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<TerrainReply>>>(AsyncGetTerrainRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<TerrainReply>>> PrepareAsyncGetTerrain(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<TerrainReply>>>(PrepareAsyncGetTerrainRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<TerrainReply>>* AsyncGetTerrainRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<TerrainReply>>* PrepareAsyncGetTerrainRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetTerrain(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, flatbuffers::grpc::Message<TerrainReply>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<TerrainReply>>> AsyncGetTerrain(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<TerrainReply>>>(AsyncGetTerrainRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<TerrainReply>>> PrepareAsyncGetTerrain(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<TerrainReply>>>(PrepareAsyncGetTerrainRaw(context, request, cq));
    }
  
   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<TerrainReply>>* AsyncGetTerrainRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<TerrainReply>>* PrepareAsyncGetTerrainRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<TerrainRequest>& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetTerrain_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
  
  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetTerrain(::grpc::ServerContext* context, const flatbuffers::grpc::Message<TerrainRequest>* request, flatbuffers::grpc::Message<TerrainReply>* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetTerrain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithAsyncMethod_GetTerrain() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetTerrain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTerrain(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<TerrainRequest>* /*request*/, flatbuffers::grpc::Message<TerrainReply>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTerrain(::grpc::ServerContext* context, flatbuffers::grpc::Message<TerrainRequest>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<TerrainReply>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef   WithAsyncMethod_GetTerrain<  Service   >   AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetTerrain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithGenericMethod_GetTerrain() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetTerrain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTerrain(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<TerrainRequest>* /*request*/, flatbuffers::grpc::Message<TerrainReply>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetTerrain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service */*service*/) {}
   public:
    WithStreamedUnaryMethod_GetTerrain() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<TerrainRequest>, flatbuffers::grpc::Message<TerrainReply>>(std::bind(&WithStreamedUnaryMethod_GetTerrain<BaseClass>::StreamedGetTerrain, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetTerrain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetTerrain(::grpc::ServerContext* /*context*/, const flatbuffers::grpc::Message<TerrainRequest>* /*request*/, flatbuffers::grpc::Message<TerrainReply>* /*response*/) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetTerrain(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<TerrainRequest>,flatbuffers::grpc::Message<TerrainReply>>* server_unary_streamer) = 0;
  };
  typedef   WithStreamedUnaryMethod_GetTerrain<  Service   >   StreamedUnaryService;
  typedef   Service   SplitStreamedService;
  typedef   WithStreamedUnaryMethod_GetTerrain<  Service   >   StreamedService;
};

}  // namespace GWDat


#endif  // GRPC_gwdat_5fterrain__INCLUDED
